name: flutter_love_provider
description: Provide flutter widgets for supporting solution base on flutter, love and provider.
version: 0.1.0-beta.1
homepage: https://github.com/LoveCommunity/flutter_love_provider

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  love: ^0.1.0
  flutter_love: ^0.1.0-beta.8
  provider: ^6.0.0
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0