name: flutter_love_provider
description: Provide flutter widgets for supporting solution base on flutter, love and provider.
version: 0.1.0
homepage: https://github.com/LoveCommunity/flutter_love_provider

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  love: ^0.2.0
  flutter_love: ^0.2.0
  provider: ^6.0.0
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1